# Use the README file as a reference to customize settings.

Page:
  fields:
    default: title, slug, image_file_name, image_file_size, description, views, adult
    form: title, slug, image_file_name, image_file_size, description, views, adult
  relationships: 
  application: Application
